model:
  loss:
    class_path: models.io.loss.Loss
    init_args:
      loss_func:
        class_path: models.io.loss.MultiResolutionSTFTLoss
        init_args:
          fft_sizes:
            - 512
            - 1024
            - 256
          hop_sizes:
            - 60
            - 120
            - 25
          win_lengths:
            - 300
            - 600
            - 120
          window: hann_window
      pit: true
      loss_func_kwargs:
        mixture_constraint: false
